export const FETCH_BROKERS_REQUEST = 'FETCH_BROKERS_REQUEST'
export const FETCH_BROKERS_SUCCESS = 'FETCH_BROKERS_SUCCESS'
export const FETCH_BROKERS_FAILURE = 'FETCH_BROKERS_FAILURE'
    
export const FETCH_BROKER_REQUEST = 'FETCH_BROKER_REQUEST'
export const FETCH_BROKER_SUCCESS = 'FETCH_BROKER_SUCCESS'
export const FETCH_BROKER_FAILURE = 'FETCH_BROKER_FAILURE'

export const INSERT_BROKER_REQUEST = 'INSERT_BROKER_REQUEST'
export const INSERT_BROKER_SUCCESS = 'INSERT_BROKER_SUCCESS'
export const INSERT_BROKER_FAILURE = 'INSERT_BROKER_FAILURE'

export const UPDATE_BROKER_REQUEST = 'UPDATE_BROKER_REQUEST'
export const UPDATE_BROKER_SUCCESS = 'UPDATE_BROKER_SUCCESS'
export const UPDATE_BROKER_FAILURE = 'UPDATE_BROKER_FAILURE'

export const DELETE_BROKER_REQUEST = 'DELETE_BROKER_REQUEST'
export const DELETE_BROKER_SUCCESS = 'DELETE_BROKER_SUCCESS'
export const DELETE_BROKER_FAILURE = 'DELETE_BROKER_FAILURE'